{
    "name": "Sales Custom",
    "version": "1.0",
    "category": "Sales",
    "author": "Sabrina",
    "summary": "Custom Sales Application with Order Information",
    "depends": ["base", "web", "hr"],
    "data": [
        "views/oi_js_close_view.xml",
        "views/experience_list_js_views.xml",
        "views/action.xml",
        "views/oi_js_view.xml",
        "views/job_item_js_view.xml",
        "views/order_information_view.xml",
        "views/job_item_view.xml",
        "views/scope_remarks_view.xml",
        "views/scope_division_view.xml",
        "views/scope_division_list_view.xml",
        "views/order_information_confirm_view.xml",
        "views/oi_js_confirm_view.xml",
        "views/order_information_list_view.xml",
        "views/oi_js_list_view.xml",
        "views/experience_list_views.xml",
        "views/order_information_export_custom_wizard_view.xml",
        "views/menu_items.xml",
        "views/order_information_close_view.xml",
        "views/oi_js_export_custom_wizard_view.xml",
    # "views/minimal_html_container.xml",
    # "views/custom_minimal_html_container.xml",
        "report/order_information_report_header.xml",
        "report/custom_paperformat.xml",
        "report/custom_paperformat_margin.xml",
        "report/order_information_report_action.xml",
        "report/oi_js_report_action.xml",
        "report/oi_js_report_corrected.xml",
        "report/order_information_report_corrected.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
    ],
    "assets": {
        "web.report_assets_common": [
            "sales_custom/static/src/image/logo.png",
        ],
        "web.assets_backend": [
            "sales_custom/static/src/js/datepicker_scroll.js",
            "sales_custom/static/src/css/datepicker_scroll.css",
            # "sales_custom/static/src/js/close_oi_confirm.js",
        ]
    },
    "installable": True,
    "application": True
}